# Generated by Django 2.0.5 on 2018-05-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango_with_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
